#
# TABLE STRUCTURE FOR: media
#

DROP TABLE IF EXISTS `media`;

CREATE TABLE `media` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `media_type_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `body` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `filename` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `size` int(11) DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `media_type_id` (`media_type_id`),
  CONSTRAINT `media_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `media_ibfk_2` FOREIGN KEY (`media_type_id`) REFERENCES `media_types` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('1', '1', '1', 'Natus aspernatur perferendis corporis illo. Quod eum eos quos est. Id sit ut sequi nesciunt vel modi.', 'corporis', 89, NULL, '1988-10-21 02:09:33', '1995-11-28 22:01:23');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('2', '2', '2', 'Aspernatur eos enim asperiores iusto. Illum quod rem et et. Repellat eligendi esse autem sed dolor molestias reiciendis eum.', 'officiis', 2909, NULL, '2019-02-22 12:03:05', '1986-03-01 18:47:17');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('3', '3', '3', 'Perspiciatis nesciunt tenetur laborum et omnis ea. Sint mollitia quas non molestiae quo nulla. Est fuga vel incidunt itaque.', 'sapiente', 2, NULL, '1992-10-04 19:05:12', '2011-06-28 20:54:48');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('4', '4', '4', 'Suscipit ullam aut exercitationem doloribus voluptatem commodi eaque. Quae et quia porro libero consectetur velit rerum. A assumenda porro magni excepturi iusto dolores soluta dolorum. Inventore modi sint at saepe pariatur.', 'enim', 589, NULL, '1978-05-22 22:14:55', '1984-11-16 16:56:52');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('5', '5', '5', 'Odit perferendis porro perspiciatis quia autem. Impedit reprehenderit fugit iste qui consequatur. Perferendis autem possimus ipsam rerum explicabo. Placeat magnam eum architecto harum rem fugiat et.', 'veritatis', 72445, NULL, '1986-10-29 02:41:55', '2007-08-17 23:46:50');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('6', '6', '6', 'Voluptate nesciunt magnam rerum voluptatem. Aliquid saepe doloremque reprehenderit et illum dolor. Hic voluptas eum ducimus.', 'quidem', 986667, NULL, '2003-01-06 02:16:53', '2005-02-28 00:55:51');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('7', '7', '7', 'Totam laborum reiciendis beatae voluptatem rerum. Eveniet et dolore doloremque est ut dicta. Quod sed nostrum est enim itaque quidem reiciendis quo. Mollitia eos illo eum in.', 'hic', 1459, NULL, '1990-09-16 01:21:08', '2008-02-07 20:29:03');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('8', '8', '8', 'Est quam iusto autem dolores iure. At fuga vero magnam quam. In fuga porro ipsam blanditiis rerum. Est ducimus tempora natus.', 'cum', 9, NULL, '2015-10-01 06:12:43', '2012-09-15 01:27:47');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('9', '9', '9', 'Commodi at molestias quos accusamus quisquam. Harum possimus nam quo sunt voluptatem velit sed. Sapiente eligendi ad quia assumenda atque.', 'omnis', 336044175, NULL, '2015-06-30 15:59:45', '2006-05-15 23:10:54');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('10', '10', '10', 'Aut sit mollitia doloremque non ad sint. Sequi corporis sequi odit laboriosam. Magnam minus fuga unde velit.', 'nobis', 779, NULL, '2017-11-19 19:55:19', '2008-03-01 08:23:02');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('11', '11', '11', 'Autem harum dolores tempore beatae molestiae. Est in et officiis maxime ex. Nam deleniti vel quis. Et sed cum sint non ab amet ipsum blanditiis.', 'voluptas', 58898016, NULL, '1980-03-16 22:21:34', '1978-01-06 22:12:06');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('12', '12', '12', 'Hic eos ut in nesciunt nostrum expedita magnam. Quia quis et deleniti quae illum.', 'qui', 880, NULL, '1987-04-26 21:52:05', '2006-09-18 00:20:05');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('13', '13', '13', 'Rerum et soluta voluptatum autem suscipit quia autem. Aut excepturi et consequatur nihil ducimus non cumque. Facere quibusdam fuga est voluptatem quidem repellendus. Vitae accusamus et accusamus ducimus.', 'consectetur', 4, NULL, '1970-07-19 19:42:12', '1991-04-17 04:34:00');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('14', '14', '14', 'Sit recusandae placeat deserunt. Et voluptate impedit ea est qui sit fugiat. Quia qui eligendi velit. Rerum animi ab omnis.', 'eveniet', 43, NULL, '1995-07-11 03:52:25', '2003-10-17 09:45:46');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('15', '15', '15', 'Illum omnis minus vero ea. Blanditiis est qui recusandae ab et non est. Necessitatibus quidem assumenda minus non corrupti perspiciatis eaque. Officia saepe culpa minus harum ut nemo.', 'magni', 102, NULL, '1997-10-04 12:53:32', '2005-03-21 20:38:46');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('16', '16', '16', 'Aliquam dolorem ut ut itaque non. Non sunt numquam molestias dignissimos voluptas. Sapiente quae explicabo in quam ullam voluptas. Totam modi ea at esse. Sequi quia omnis molestiae ut ex sunt.', 'quo', 0, NULL, '1993-12-24 16:02:23', '1996-05-07 07:44:26');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('17', '17', '17', 'Dicta error repellat nihil tempore autem distinctio. Id quam quasi rerum deserunt molestiae excepturi quibusdam expedita. Voluptatem eos quaerat error distinctio.', 'tempora', 328, NULL, '1996-06-28 23:34:57', '2008-04-28 19:04:31');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('18', '18', '18', 'Earum temporibus nostrum dolores fugit. Saepe iste est qui eum. Quas a ut est accusamus nesciunt quibusdam non. Necessitatibus eum cumque sit et.', 'in', 5974958, NULL, '1997-11-25 23:52:27', '1984-06-23 17:19:13');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('19', '19', '19', 'Est dicta laborum omnis sint sunt repellat inventore a. Et minima nobis ab. Sapiente sint magnam fugiat veniam magni debitis.', 'modi', 733, NULL, '2006-12-30 01:34:18', '2001-02-11 19:08:11');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('20', '20', '20', 'Occaecati debitis tempora quo sequi. Temporibus aut ut ea quibusdam similique tempora. Ea quis ut vitae cumque occaecati voluptatum. Laborum nulla unde qui temporibus ad accusamus aliquid.', 'odio', 466, NULL, '1996-09-01 17:41:17', '1975-11-29 17:46:03');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('21', '21', '21', 'Aut ut neque asperiores ullam dicta repellat et. Cum aperiam sint voluptatem non ipsa eaque. Velit voluptates perferendis non est accusamus neque tenetur.', 'et', 764, NULL, '1981-02-09 13:53:15', '1994-01-18 16:28:21');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('22', '22', '22', 'Et et eum rerum deleniti omnis voluptas ut laudantium. Reprehenderit labore provident eveniet quo. Reprehenderit aliquid soluta et enim recusandae. Ratione eos ipsam fuga doloribus.', 'sit', 45481, NULL, '1991-06-07 01:36:00', '2014-08-08 19:34:23');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('23', '23', '23', 'Tempore iste ad dolor rerum enim sed. Hic fuga magni possimus ex at. Sed sed sint sit. Nihil veniam voluptate qui vel reiciendis qui dolores.', 'mollitia', 76583, NULL, '1979-03-07 19:51:18', '2003-11-05 17:34:55');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('24', '24', '24', 'Fuga repudiandae quo eos illo tempora cum. Quod dolore earum deleniti perspiciatis reprehenderit. Repudiandae fugiat ad laborum ut illo sint. Nulla qui ad placeat est qui minus.', 'voluptatem', 7910427, NULL, '1987-06-29 00:24:54', '1984-12-21 07:50:21');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('25', '25', '25', 'Aut mollitia et architecto distinctio dolor autem consequatur. Temporibus vitae inventore consequatur et ex fugit. Consequatur voluptatem sint saepe mollitia. Pariatur vitae sed autem ab dignissimos sint nihil non.', 'facilis', 555891689, NULL, '2007-09-22 01:08:16', '2000-05-13 11:01:05');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('26', '26', '26', 'Dolor aspernatur ipsa consequatur quos iusto est. Alias reiciendis earum voluptatum et. Rem qui autem rerum quia quod.', 'molestias', 4000435, NULL, '1991-09-02 17:23:17', '2008-04-18 04:38:52');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('27', '27', '27', 'Sunt asperiores illum optio facere eligendi quos sequi. Consequatur neque quas soluta error nostrum consequatur earum quibusdam. Tempore molestiae et et distinctio placeat qui. Velit tempora ipsum repellendus sit odio enim saepe.', 'cupiditate', 51063, NULL, '2006-12-10 13:19:42', '1987-06-07 07:46:55');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('28', '28', '28', 'Sit iste est in doloremque vero error dolorem. Et officia pariatur sit. Atque voluptates ut eos et.', 'voluptatum', 26444223, NULL, '1980-12-12 06:12:57', '2000-12-01 02:23:59');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('29', '29', '29', 'Voluptatem qui et temporibus vitae sunt voluptas. Et id occaecati quam qui commodi nemo dolorem. Ut quasi quia in aut consequatur quis velit. Veritatis maxime similique aliquid enim fugiat.', 'alias', 0, NULL, '1976-10-03 20:58:21', '1990-11-01 08:46:05');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('30', '30', '30', 'Optio culpa consequatur ipsam laborum. Officiis amet ipsam itaque veniam dolorem. Ut dolor ut ea.', 'quisquam', 868439242, NULL, '1999-01-03 08:42:32', '1984-02-02 10:03:53');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('31', '31', '31', 'Sapiente nulla quasi ab qui. Maiores impedit earum possimus dignissimos fugit. Earum natus autem consequatur assumenda eligendi animi.', 'suscipit', 7480673, NULL, '1998-03-21 13:12:03', '1995-12-22 01:19:10');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('32', '32', '32', 'Dolor quas et facere ducimus ut aut adipisci. Corporis non magnam praesentium tenetur magnam sit cumque. Consequatur eveniet itaque possimus voluptatem itaque voluptatem. Quis porro earum tempore et quis.', 'qui', 531001058, NULL, '2010-12-01 04:03:12', '2001-01-01 07:52:04');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('33', '33', '33', 'Et recusandae labore omnis veritatis beatae non aspernatur ipsa. Sed molestiae temporibus est blanditiis et iusto. Beatae rerum qui nobis vero praesentium. Molestiae omnis sit tempore doloribus dolores mollitia.', 'est', 471278085, NULL, '2012-02-01 10:50:36', '1979-12-15 00:49:03');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('34', '34', '34', 'Laborum quis sint dolor in unde. Magnam molestias consequatur autem reiciendis harum esse ut. Voluptatibus odit voluptas ipsam aliquam enim.', 'ratione', 5190116, NULL, '2017-12-02 13:00:37', '1980-10-04 16:04:24');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('35', '35', '35', 'Nam eos quibusdam maxime consequatur. Quod sed eligendi quis assumenda dolor. Est laboriosam rerum sapiente molestiae doloremque. Et dolore placeat sed iure et itaque aut et.', 'voluptatem', 3123925, NULL, '2005-05-27 06:58:45', '2003-09-26 17:59:55');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('36', '36', '36', 'Impedit quia quis rerum consequatur. Vel dolores non omnis cumque. Sed vel rerum alias voluptatem id.', 'ullam', 2337, NULL, '1978-04-29 03:27:57', '1994-06-23 13:28:19');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('37', '37', '37', 'Rem eum velit et optio non qui. Neque in ut molestiae harum sunt corrupti. Odio cumque vitae accusamus sapiente et debitis. Modi explicabo nihil unde.', 'adipisci', 641, NULL, '1971-05-10 10:48:27', '1980-11-07 22:11:00');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('38', '38', '38', 'Dolore repudiandae suscipit et voluptatem. Magnam mollitia inventore perferendis nobis consequatur error. Blanditiis saepe perferendis rerum sit dolorem. Odio autem quo nam recusandae id nostrum.', 'rerum', 800900, NULL, '2007-07-14 11:56:36', '1992-11-26 09:19:21');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('39', '39', '39', 'Quos perspiciatis cupiditate ratione et voluptatem quis. Unde eaque modi nisi ab dignissimos. Ducimus ut consequatur nihil qui blanditiis iure quisquam. Est necessitatibus laboriosam eaque corporis veritatis ut deserunt.', 'libero', 15780, NULL, '1977-06-10 11:34:53', '1995-08-04 19:12:58');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('40', '40', '40', 'Et rem facilis fugit sed et quasi. Omnis autem ducimus reprehenderit et atque odit. Totam laborum repellat modi officiis et.', 'doloribus', 594, NULL, '1984-03-29 23:59:21', '1979-11-06 22:10:46');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('41', '41', '41', 'Laudantium assumenda in maiores quia id ratione adipisci. Minima qui doloribus debitis at. Repudiandae blanditiis rerum omnis asperiores.', 'rem', 7, NULL, '1993-10-22 17:07:24', '1977-04-09 00:32:29');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('42', '42', '42', 'Neque id aut porro error aut voluptatem vel. Autem expedita corrupti quia qui dolorem quam. Dolore quibusdam ullam occaecati deserunt rem.', 'quia', 46164, NULL, '1985-01-02 05:27:37', '1974-03-05 17:05:43');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('43', '43', '43', 'Perspiciatis aut fugiat voluptatum qui. Saepe placeat earum asperiores eos aperiam possimus quas qui. Quae nihil quos quasi dolore illum. Dicta temporibus quod qui amet quo voluptas rem.', 'velit', 245610752, NULL, '1996-08-02 05:31:05', '1984-10-13 15:16:48');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('44', '44', '44', 'Fugit deserunt culpa quod deserunt velit vero. Molestiae maiores dolores dolores sit minima. Voluptatem quia molestiae dolor perspiciatis fugiat et consequatur explicabo. Voluptas occaecati eos dolor autem.', 'corporis', 329513578, NULL, '1971-04-04 05:10:03', '2009-01-13 02:37:44');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('45', '45', '45', 'Amet ea occaecati laborum doloremque. Distinctio aspernatur fugit rerum quo et inventore animi blanditiis. Non dicta sint vel labore. Asperiores voluptatem maxime quod nisi eos tempore. Quaerat saepe cum et vero ut earum.', 'quia', 3736, NULL, '2001-07-06 22:10:37', '2013-09-04 03:52:52');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('46', '46', '46', 'Pariatur hic laboriosam voluptatem. Officiis voluptas quos consequatur vel ut suscipit dolores. Eum consequuntur nihil eligendi quo fuga odit neque. Dolores cum ipsa eaque voluptatibus est.', 'id', 8740511, NULL, '1996-02-04 13:23:53', '1995-07-04 15:18:06');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('47', '47', '47', 'Dolorem sed consectetur labore commodi fugit. Optio et natus consequuntur asperiores laborum quis aut. Ducimus velit nulla distinctio necessitatibus. Sunt dolores minima distinctio aut nesciunt fugit tenetur.', 'rerum', 48807, NULL, '1995-05-09 01:17:16', '2010-02-16 06:26:56');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('48', '48', '48', 'Non cumque voluptas modi quis et aut error. Officia sint eum molestiae sint quis.', 'soluta', 9487492, NULL, '1980-11-23 06:08:20', '2003-12-26 19:30:13');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('49', '49', '49', 'Qui illum repellat officiis nisi. Quae recusandae quaerat assumenda cupiditate architecto. Ut et in vero est. Earum et error quo distinctio nam iste ab.', 'eum', 398588, NULL, '2012-03-24 22:40:39', '1997-09-10 09:49:07');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('50', '50', '50', 'Velit odit dolore et nostrum. Magnam optio voluptatem molestiae non id et. Est in officiis deleniti et.', 'eos', 412356933, NULL, '1976-06-14 04:34:50', '1981-11-30 02:23:13');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('51', '51', '51', 'Mollitia labore dolore consequatur eligendi aut error saepe. Neque modi eos saepe exercitationem unde. Aspernatur molestias hic alias.', 'perspiciatis', 0, NULL, '1995-10-25 02:47:38', '1998-02-02 07:07:41');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('52', '52', '52', 'Distinctio quae dolores numquam deleniti incidunt ullam. Iste itaque ad id beatae perferendis. Est fugiat est qui.', 'ut', 8, NULL, '2019-11-12 06:50:07', '1986-06-08 12:26:43');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('53', '53', '53', 'Id est nisi inventore libero esse. Aut sit accusamus facilis. Sunt quas nihil iste accusamus explicabo dolor.', 'quod', 489, NULL, '1988-09-08 15:45:09', '1988-05-03 23:29:45');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('54', '54', '54', 'Autem et enim et eum qui. Molestiae sunt repellendus voluptatem molestiae cupiditate delectus. Modi quas consequatur sint ipsum a ut sunt.', 'eum', 1352, NULL, '2017-08-05 19:09:49', '1988-04-27 16:27:25');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('55', '55', '55', 'Eum et quo officia incidunt ipsam. Quod molestiae magnam quis nihil rem impedit.', 'voluptatem', 652, NULL, '1973-07-19 22:28:15', '2002-06-20 15:21:59');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('56', '56', '56', 'Commodi qui minima neque similique voluptas ducimus. Laudantium sequi sequi iure corrupti culpa expedita. Cupiditate delectus odio dolorem eaque ipsum laboriosam. Expedita quo est aut est. Voluptas laborum cum et qui.', 'nesciunt', 0, NULL, '2002-07-12 14:16:41', '2009-11-03 21:42:47');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('57', '57', '57', 'Tempore animi suscipit vero occaecati. Aut tempora sint et. Quia et quo magni. Voluptas excepturi velit sint nobis.', 'veritatis', 2, NULL, '1998-07-23 08:32:48', '1973-01-24 07:28:48');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('58', '58', '58', 'Maxime illo illo nam dolorem omnis est ratione. Maxime commodi at quos culpa voluptatibus. Qui excepturi cum sed et modi. Distinctio ut sequi quam dolores adipisci consequuntur sed.', 'aut', 44, NULL, '1993-11-25 16:38:26', '2015-05-29 18:09:02');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('59', '59', '59', 'Impedit nobis est inventore autem. Sed assumenda id vero praesentium. Alias laborum voluptas quibusdam atque vero ut. Eveniet omnis laboriosam fugit rerum odio excepturi facilis.', 'est', 83282, NULL, '1982-01-08 02:29:48', '1975-11-19 11:32:44');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('60', '60', '60', 'Ut aut culpa sit aliquid et exercitationem. Excepturi dolorem ullam quasi aut perferendis. Maiores reprehenderit inventore ea reiciendis explicabo adipisci. Vel facilis error dolores blanditiis facere officiis sunt.', 'dolorem', 31168, NULL, '1973-05-13 05:54:59', '1984-07-29 17:59:49');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('61', '61', '61', 'Ea et ipsum perspiciatis minus magni qui recusandae. In quia consequuntur cumque provident autem minus nihil. Qui possimus accusantium dolor fugit commodi. At dolor dolorem sed et. Ea veniam dolore ut culpa est aut rerum.', 'officiis', 846332, NULL, '2005-06-23 18:48:56', '1984-12-25 01:39:56');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('62', '62', '62', 'Soluta veritatis est quam sequi officia dolor nisi. Ea sed qui occaecati exercitationem quae et molestias velit. Ut dignissimos qui molestiae consequatur.', 'dolor', 0, NULL, '2000-10-12 04:50:02', '1986-06-19 16:02:05');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('63', '63', '63', 'Fugit harum sed aut accusantium consequatur nostrum. Fugit eaque ut non et recusandae blanditiis quia. Animi corrupti ea occaecati.', 'rerum', 73020, NULL, '2002-10-23 23:53:17', '1974-02-20 09:18:43');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('64', '64', '64', 'Velit est aspernatur est eos aut eligendi consequatur. Et aut quaerat est. Et sequi qui voluptate architecto quia iste.', 'ipsam', 562, NULL, '1995-10-20 23:08:29', '1989-03-03 15:35:24');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('65', '65', '65', 'Dignissimos aut voluptas error sed. Tempore recusandae beatae est corporis fugiat. Ea blanditiis quisquam pariatur est sunt molestiae.', 'doloremque', 961132, NULL, '2019-10-20 02:01:39', '1997-07-18 12:05:34');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('66', '66', '66', 'Enim aspernatur error nam. Repellendus ad sint corrupti harum quo adipisci cupiditate iusto. Adipisci ut aut minima eveniet. Sed nemo nisi nostrum autem quam.', 'tenetur', 2, NULL, '1984-07-08 20:28:54', '1995-09-28 09:30:51');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('67', '67', '67', 'Et repellat distinctio optio et impedit dolores. Enim eaque nesciunt eligendi saepe consectetur est aspernatur.', 'saepe', 63123, NULL, '1971-03-05 23:28:29', '1974-10-15 07:54:42');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('68', '68', '68', 'Voluptatem iusto consequatur sunt veniam molestiae dolores provident. Fugiat doloremque eligendi fugit consequatur tempora quam. Inventore eius architecto qui voluptatem aliquid.', 'molestiae', 4, NULL, '1992-11-26 07:24:09', '2005-12-13 19:59:31');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('69', '69', '69', 'Commodi eius aut nihil exercitationem. Perspiciatis quas omnis sint vero quis perferendis. Nam laborum at aut nemo. Non consequatur qui accusantium ea culpa aspernatur repellendus labore.', 'dolores', 1982, NULL, '1973-06-14 09:38:53', '1995-05-10 03:23:03');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('70', '70', '70', 'Aliquam earum ea in aut. Deleniti officiis id et ut minima accusamus placeat. Rerum provident mollitia odit facere. Temporibus hic eum consequatur tempora illo qui. Aut dolorem perspiciatis praesentium repellat eum.', 'itaque', 7790, NULL, '2017-07-18 02:55:06', '2014-08-13 06:37:56');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('71', '71', '71', 'Laudantium saepe aut consequatur libero ut aut. Maiores aut cupiditate officia accusantium. Qui ea tenetur aliquam ex. Deleniti voluptas quo aut ipsum.', 'est', 52, NULL, '1981-02-14 00:00:39', '1998-09-05 21:56:45');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('72', '72', '72', 'Enim consequuntur officia inventore. Cupiditate illo autem earum rerum voluptatibus omnis. Est deserunt expedita expedita qui dolor dolores aut.', 'facilis', 8, NULL, '1979-06-03 15:10:16', '2007-04-29 20:38:22');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('73', '73', '73', 'Sit fugit aspernatur molestias porro dolor et pariatur. Non voluptatem ab id autem ullam. Quam qui earum iste reprehenderit. Ea qui quo quasi eos aperiam saepe.', 'quia', 78, NULL, '2005-12-01 06:54:10', '1980-10-20 06:52:21');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('74', '74', '74', 'Aut eaque deleniti minus. Aut itaque quod numquam ab. Ut hic qui quae architecto possimus non pariatur.', 'libero', 8054795, NULL, '2019-06-04 04:30:33', '1997-09-29 04:20:05');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('75', '75', '75', 'In sed animi ratione blanditiis quaerat accusamus voluptatem. Id nulla dolore et at. Illum deserunt et numquam provident molestiae eaque necessitatibus.', 'harum', 7806448, NULL, '1976-03-19 21:35:17', '2006-08-02 15:15:52');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('76', '76', '76', 'Id et facilis ab voluptatem velit. Officia et maxime incidunt eligendi. Eos accusantium ullam rem excepturi veritatis cumque labore. Facilis molestias voluptatibus vitae saepe quisquam.', 'et', 774, NULL, '2011-04-17 20:33:01', '1970-01-06 21:09:55');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('77', '77', '77', 'Repellat praesentium rerum aut ipsam dolore nesciunt repellat. Asperiores eum ut dolorem voluptates. Exercitationem dolore quis a enim. Quam optio quia autem soluta quasi sunt. Dolorum dicta nihil quasi pariatur.', 'sit', 3959, NULL, '1973-09-18 14:10:29', '2010-04-19 19:29:28');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('78', '78', '78', 'Maxime quia inventore dolorem aut magnam et dolore. Ea ipsam ex sit dolorem. Provident rerum corporis eos sit. Architecto sunt eum voluptas asperiores esse omnis veniam aliquam.', 'aut', 5044, NULL, '2017-04-23 14:01:14', '2013-11-27 23:23:44');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('79', '79', '79', 'Aut neque odit ea vitae vel. At sed qui ut alias reiciendis beatae tenetur. Sit voluptatum tempora provident voluptatem perspiciatis.', 'et', 137719992, NULL, '1999-10-27 14:28:29', '1985-02-12 15:22:21');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('80', '80', '80', 'Quia assumenda non et facilis et doloremque ducimus. Cupiditate qui molestiae voluptatibus amet totam suscipit consequuntur occaecati. Nisi sequi possimus eligendi.', 'debitis', 202152404, NULL, '2009-08-13 03:03:26', '1997-04-02 08:10:37');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('81', '81', '81', 'Ut eius ut quasi dolores nemo. Et corporis tempora distinctio quasi eveniet alias. Ut ut officia voluptates exercitationem qui eveniet enim.', 'a', 839570, NULL, '2010-08-10 01:38:30', '1992-02-04 09:08:53');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('82', '82', '82', 'Quae recusandae et ut sint. Iusto assumenda quia doloribus dolor eos alias. Corporis consequatur velit nesciunt nobis dolor. Molestiae ipsam reiciendis non maiores.', 'reiciendis', 35269, NULL, '1971-12-08 20:10:39', '1974-04-14 13:12:48');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('83', '83', '83', 'Eaque officia explicabo quos repellat sit. Dignissimos illo ducimus ut dicta facilis. Et et enim id voluptatem itaque sed id.', 'eius', 5971, NULL, '2012-04-15 19:34:13', '1970-07-07 05:03:01');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('84', '84', '84', 'Enim doloribus iure at labore nesciunt praesentium cupiditate et. Rerum pariatur consequatur enim eaque est. Sapiente quo quod rerum enim.', 'quia', 7999, NULL, '1977-04-30 18:29:09', '1984-06-16 20:13:36');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('85', '85', '85', 'Accusamus commodi sit voluptas. Aut autem est sunt nihil autem culpa.', 'harum', 814814117, NULL, '2013-10-10 10:15:05', '2001-11-25 03:44:28');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('86', '86', '86', 'Perspiciatis incidunt iusto modi sed quia sunt. Itaque officiis autem nam est. Consequatur pariatur dolores et rem dolores ratione quibusdam.', 'quidem', 33, NULL, '1974-08-15 12:10:21', '1977-05-31 05:35:35');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('87', '87', '87', 'Molestiae in distinctio et. Quaerat facilis cupiditate at libero eum. Rerum ut corrupti rerum distinctio eligendi.', 'rerum', 3977, NULL, '1998-08-31 18:44:18', '1979-08-08 08:11:00');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('88', '88', '88', 'Quisquam veritatis illum consequuntur quod debitis sed. Eos ipsam ea explicabo minus tempora minus occaecati. Consequatur nesciunt sequi eos sapiente.', 'autem', 2708849, NULL, '2009-11-24 09:18:33', '1989-05-13 15:30:33');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('89', '89', '89', 'Consequatur ipsum sed enim est laudantium maiores et. Quasi vel suscipit quas assumenda quam veritatis. Et maiores magnam beatae eius adipisci. Sit vel illum consequatur vel. Dolore est nisi nihil reiciendis assumenda esse asperiores.', 'illo', 0, NULL, '2004-02-16 13:05:56', '1988-10-23 20:39:38');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('90', '90', '90', 'Ut veniam perferendis cupiditate consequuntur aut autem sit. Distinctio at quia provident. Aut rem similique tenetur eveniet et harum.', 'necessitatibus', 395, NULL, '1998-09-21 09:38:02', '1972-09-05 02:06:44');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('91', '91', '91', 'Molestiae enim qui aut qui. Est ducimus et hic architecto ab. At veritatis a accusamus sunt cumque sunt magnam. Est quis error iure voluptas voluptatem nisi. Esse labore iure quia dolore labore impedit dolores sed.', 'ut', 35, NULL, '2004-11-08 19:55:01', '1987-09-25 08:28:58');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('92', '92', '92', 'Et quia tempore illum enim. Voluptatibus numquam neque suscipit. Non pariatur excepturi architecto ducimus ipsum rerum et aliquid. Omnis et aliquid temporibus animi magni esse.', 'ipsam', 25, NULL, '1991-02-18 23:46:00', '1992-01-03 13:20:19');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('93', '93', '93', 'Enim voluptates sint molestiae. Consectetur et impedit sit vel illo amet quidem in. Fugiat nisi qui voluptates odit quia. Sint alias autem delectus.', 'sit', 1412408, NULL, '1984-03-06 12:34:07', '2016-03-25 19:55:24');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('94', '94', '94', 'Rem facilis corporis sit quasi laboriosam nesciunt dolor. Sed rerum ad et voluptate corrupti. Distinctio ipsum sint sapiente aperiam. Velit quae possimus odit eos debitis cum.', 'quis', 2, NULL, '1980-02-07 20:19:05', '1974-08-08 03:31:44');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('95', '95', '95', 'Ullam omnis voluptatem nihil voluptas. Ducimus eligendi adipisci atque nisi non. Voluptatibus odit ut sit totam.', 'et', 7, NULL, '2014-05-09 13:34:29', '1987-04-06 21:51:20');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('96', '96', '96', 'Sunt nisi molestiae ullam id necessitatibus. Dolorem commodi officia dolorem neque in. Debitis quis ex est dolor inventore hic.', 'harum', 644653, NULL, '1979-10-22 06:22:11', '2018-11-02 17:48:26');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('97', '97', '97', 'Distinctio ut facilis aut. Qui consequuntur vel atque. Repudiandae et magnam nihil porro consequuntur est rerum.', 'esse', 0, NULL, '2002-12-13 22:31:04', '1990-08-14 01:33:37');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('98', '98', '98', 'Doloremque eaque nobis vel rem quia provident aut. Accusamus atque et dolorem ut alias fugit eum. Et vero sit dolorum iure quasi consequatur. Consequatur voluptatem et doloribus quis nam rerum quidem necessitatibus.', 'sequi', 90, NULL, '2010-08-14 22:34:11', '2013-10-16 09:28:11');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('99', '99', '99', 'Exercitationem sint quos inventore eaque omnis beatae rerum voluptatem. Voluptas voluptatem repellat asperiores voluptatum delectus. Eveniet officia voluptatem officia suscipit. Illum corrupti ex laborum et cupiditate.', 'error', 48686565, NULL, '2015-10-03 11:58:28', '1992-04-11 09:48:40');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('100', '100', '100', 'Minus nam perspiciatis vel. Et non sapiente dolorum veniam.', 'est', 9864558, NULL, '2012-09-30 17:06:28', '1981-10-26 19:12:28');


